DATABASE_USER: root
DATABASE_PASSWORD: nacho
DATABASE_HOST: localhost
DATABASE_PORT: 3306
DATABASE_ENGINE: django.db.backends.mysql
DATABASE_NAME: Dssd_coupons_app

SECRET_KEY: 'n)8a*_q#z8b&mqhnmk0e2=jhab#7)xh5nir(spa2inprd^vo6m'