# Generated by Django 2.1.1 on 2018-10-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='availability',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
